### Register a User ##
POST {{baseUrl}}{{contextPath}}/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "user@example.com",
    "username": "sampleUser",
    "password": "securePass123",
    "role": "ADMIN"
}

### Generate a Token
POST {{baseUrl}}{{contextPath}}/auth/token HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}

### Get Resources
GET {{baseUrl}}{{contextPath}}/resources HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3NjM4MzMyMDgsImV4cCI6MTc2MzgzNjgwOH0.1SCXVKp8LfkdrgDYVM1-MIyFkJxGPcdUxeYt1VeiO32ss7LZNsoK4bZOOVV5jBCa26CoM7U9oMGhWSPxvVhVpw

